### ISSUE TITLE
Why don't use String in add_template?

### ISSUE THREAD

**Issue by cathaysia** [mitsuhiko/minijinja#257]
The parameter of the add_template function is a string reference with a lifetime. Why not use String to move the value here? Dealing with lifetime is not pleasant by any means.

For rust, the exact type of a function parameter depends on whether it needs to own it. It's not a good idea to just get a reference where then function need own it.

**Comment by mitsuhiko** [comment]
You can use a `Source` to avoid the lifetime issues: https://docs.rs/minijinja/latest/minijinja/struct.Source.html

The short answer is that not having that lifetime there makes the system self referential. Long answer is that this is a rather hard problem to solve and to support the `source` feature two external dependencies are used: `self_cell` and `memo-map`. Since not everybody needs this, I opted to making it optional. The API also surprisingly hard to resolve properly, given how some of the internals work. There is a ticket open to improve this #135 but all my attempts to address this have made the internals incredibly messy.

**Comment by cathaysia** [comment]
Ok, thanks.
