### ISSUE TITLE
Support for formatting dates

### ISSUE THREAD

**Issue by rgwood** [mitsuhiko/minijinja#303]
Hello, thanks for writing+maintaining Minijinja; it's really great!

I often need to format dates in my templates. For examples, say I have a `chrono::NaiveDate` in Rust and I want to display it like "May 1, 1980" in the template. [As far as I'm aware, there is currently no great way to do this in Minijinja](https://github.com/mitsuhiko/minijinja/discussions/290) (hopefully I'm wrong).

[Tera has a `date` filter for this](https://tera.netlify.app/docs/#date), behind [a feature](https://github.com/Keats/tera/blob/master/Cargo.toml#L52) so that users can opt out of the `chrono` dependency. It's pretty useful.

Would it make sense to add similar date formatting functionality to Minijinja?

**Comment by mitsuhiko** [comment]
I already wrote such a filter a few times and was close to adding it to minijinja-contrib. I’m in favor of adding it.

I think one might want to generate that filter from a factory function in order to give it a default format string. This type of filter also runs into the issue of having to support the different serialization formats or chrono and time and it also brings up the topic of i18n/l10n.

The sum of those issues was why I didn’t dare to go down that path yet.

**Comment by mitsuhiko** [comment]
Another option could be to store the default config just in the template context. Eg reserve `LOCALE` and `TIMEZONE` etc.

**Comment by mitsuhiko** [comment]
I think something like the following might work. A new filter `datetimeformat` is added. It takes a `&State` and `Value`. The `Value` is converted from any of the formats that `chrono` or `time` serialize to (ISO string, ordinal tuples etc.).

For formatting it can take a format string (format TBD) and if it's missing, it's picked from the context from the global `DATETIME_DEFAULT_FORMAT` variable. Likewise the timezone is picked up from `TIMEZONE` and the locale from `LOCALE` (if support for that is added).

For formatting it's unclear what it can use to format. The obvious choices i think are `icu_datetime` or `chrono` with `unstable-locales` (seems unmaintained sadly). The `time` crate also has some formatting capabilities these days but it does not seem to support locales.
