### ISSUE TITLE
Support for Dict Methods (keys, values, items)

### ISSUE THREAD

**Issue by bertjwregeer** [mitsuhiko/minijinja#32]
I am using this in a small tool to render configuration files, and want to be able to more easily translate existing knowledge of Jinja2 from Python to minijinja.

I am looking to do something like, which does not work:

```
{% for (k, v) in env.items() %}
{{ k }}: {{ v }}
{%- endfor %}
```

```
Error { kind: ImpossibleOperation, detail: Some("object has no method named items")
```

This does work:

```
{% for k in env %}
{{ k }}: {{ env[k] }}
{%- endfor %}
```

So I have a work-around for now. 

I did see this closed issue: https://github.com/mitsuhiko/minijinja/issues/9 however there is no `items` filter.

Is there a way to add some of the more useful functions, such as `keys()`, `items()`, or `values()` on maps?

**Comment by mitsuhiko** [comment]
It’s something I’m in fact considering but I worry a bit about where this might lead. For now you can use the `|dictsort` filter.

**Comment by mitsuhiko** [comment]
So this could be implemented. One kinda odd consequence is that in Jinja2 `foo.items` often is ambiguous because it can both address into `foo` as an item or attribute lookup. In MiniJinja this problem does not exist at the moment because maps and structs don't have attributes on them. Interestingly because of how I choice to implement method calls `foo.items()` is a method call in MiniJinja and `foo.items` is an attribute lookup so it's possible to disambiguate them.

I am however not sure how I feel about this. I figured `|dictsort` is a good compromise because it exists in both Jinja2 and MiniJinja but I can see `.items()` being very popular in templates.

Related one issue is that MiniJinja currently loses the original order of structs and maps because it feeds everything into a `BTreeMap` which loses order. It might be interesting to try to have something like a `preserve_order` feature like `serde_json` which uses `indexmap`.

**Comment by bertjwregeer** [comment]
I honestly don't mind losing the original order for keys in a map. I have never relied on them being in a particular order in the first place, but I also understand that I may be an outlier.

`.items()` was the first thing I tried taking a Jinja2 template I used in a Python project, and thus was kind of surprised I got an error and went hunting for a work-around.

I see why you would be hesitant to add it, since it is directly adding Python behavior/methods on top of Rust, but it may help reduce support costs from a "least surprise" when trying to use this library.

**Comment by mitsuhiko** [comment]
I think I'm not completely opposed to the idea but I think I want to explore a bit what other methods actually call that leak out from Python so I get a better idea what I'm signing up for.

**Comment by bertjwregeer** [comment]
I am going to play around a little bit more with existing templates I have, to get a better idea for what I may be missing! Thanks for the consideration!

**Comment by mitsuhiko** [comment]
I think these are the potentially interesting methods:

* `str.replace` (`|replace` exists)
* `str.format` (I see this used a lot, but that is a lot of work to implement)
* `str.startswith` (same as `is startingwith`)
* `str.endswith` (same as `is endingwith`)
* `str.strip` (same as `|trim`)
* `str.lstrip` / `str.rstrip` (no equivalent)
* `str.split` (this one is probably quite useful)
* `str.splitlines` (this one is probably useful)
* `str.title` / `str.capitalize` (no equivalent but could be a filter)
* `str.lower` / `str.upper` (filter equivalent in `|upper`, `|lower`)
* `dict.values` (not sure how useful this is)
* `dict.keys` (same as direct iteration but creates a list)
* `dict.items` (seems useful, but could in theory be a filter)

**Comment by mitsuhiko** [comment]
I an not considering this closed, but the `|items` filter landed in main.
