### ISSUE TITLE
Cargo.lock file for minijinja-cli binary

### ISSUE THREAD

**Issue by psibi** [mitsuhiko/minijinja#376]
## Description

I'm trying to package minijinja-cli as part of nixpkgs. Unfortunately it doesn't work since there is no `Cargo.lock` file present. But it does like there is a different file named `Cargo.lock.msrv` present in the root of the repository.

## Reproduction steps

Trying to buid it via my nix script throws this error:

```
...
ERROR: The Cargo.lock file doesn't exist

Cargo.lock is needed to make sure that cargoHash/cargoSha256 doesn't change
when the registry is updated.
```

I can share my nix derviation files if required, but I'm not sure if it would be helpful.

Additional helpful information:

- Version of minijinja: Not applicable
- Version of rustc: Not applicable
- Operating system and version: NixOS

## What did you expect

An easy fix for this would be to rename the existing `Cargo.lock.msrv` to `Cargo.lock` file.

**Comment by mitsuhiko** [comment]
I'm aware of this issue but I'm not sure how to resolve it. The proposal to rename `Cargo.lock.msrv` is bad, because then it means that the unittests only run against the locked version which is not what I want. The only known solution for me is to move the cli out of the workspace. That however has other consequences I'm not okay with.

**Comment by psibi** [comment]
How about having the file as `Cargo.lock` in the repository and in the CI, you can do `rm Cargo.lock` (or `mv Cargo.lock Cargo.lock.msrv`) before the required check happens ?
