### ISSUE TITLE
2.0: Figure out Value::from_object_iter

### ISSUE THREAD

**Issue by mitsuhiko** [mitsuhiko/minijinja#453]
The method does not make a ton of sense to me right now. Things to figure out:

* `unsafe`: is this actually safe if you pass non `Object` values?
* Why does `get_value` return a clone of the key. Evidently returning something other than `None` here makes the tests pass, but returning the key seems wrong

**Comment by SergioBenitez** [comment]
I can provide some insight here.

The idea behind `from_object_iter` is basically to allow creating self-referential iterators. This is particularly useful when the thing you're self-referencing is an object, but it need not be.

> unsafe: is this actually safe if you pass non Object values?

Yes, if it's safe, it's safe for the bounds set. In other words, the safety doesn't rely on anything constrained to `Object`.

> Why does get_value return a clone of the key. Evidently returning something other than None here makes the tests pass, but returning the key seems wrong

Right now it returns the key because the key is the next item in the iterator. This is because `enumeration` returns the iterator itself, so the `key`s passed into `get_value()` are the items produced from the iterator.

**Comment by mitsuhiko** [comment]
Ah yeah, I see the iteration behavior now. I want to think about this iteration protocol a bit more. It feels like it has some holes at the moment.

**Comment by mitsuhiko** [comment]
This is now cleaner as it follows the new custom iteration protocol.
