### ISSUE TITLE
2.0: EnumerationIter cannot be DoubleEndedIterator

### ISSUE THREAD

**Issue by mitsuhiko** [mitsuhiko/minijinja#455]
At the moment `EnumerationIter` assumes that it can be a double ended iterator. For real iterators that's not possible.

* Is this trait necessary?
* Should this be exposed in other ways?

**Comment by SergioBenitez** [comment]
That trait `impl` is how the `rev()` filter works.

My idea for improving this was actually to add a fallible `reversible_iter()` method to `DynObject` that returned a `DoubleEndedIterator` only when it was possible to do so correctly. This is a little trickier to implement than to state, because you also want the producer of the enumeration iterators to be able to tell you what kind of iterator they have.

In practice, it seems there are two properties of interest that each may or may not apply to an iterator: whether it has a known size, and whether it is double-ended. This would imply that to be precise, one would need to have a variant for each pair (4 variants in total). But perhaps the case of unsized + reversible is uncommon enough to not be interesting.
