### ISSUE TITLE
Don't allocate to `reverse`

### ISSUE THREAD

**Issue by SergioBenitez** [mitsuhiko/minijinja#462]
Mostly opening this to track the TODO. Currently we have:

```rust
            // TODO: support reversible iterators?
            let mut values = iter.collect::<Vec<_>>();
            values.reverse();
            Ok(Value::from_iter(values))
```

Which is rather unfortunate. It would be nice to do this without allocation. (Also, does this handle infinite iterators correctly, or will it exhaust memory?)

**Comment by mitsuhiko** [comment]
Yeah, I would be very nice to support reversible iterators properly. The `|reverse` filter even in Jinja2 already returns an iterator so that is fine to support without buffering without making templates incompatible.

I don't have a great idea yet for how to support reversing without a lot of complexity though :(
