### ISSUE TITLE
2.0: Rename Value::from_serializable

### ISSUE THREAD

**Issue by mitsuhiko** [mitsuhiko/minijinja#469]
That name annoys me from the beginning of time.  I think a better name would at least be `Value::from_serialize`.

**Comment by SergioBenitez** [comment]
In Figment, I call it [`Value::serialize()`](https://docs.rs/figment/latest/figment/value/enum.Value.html#method.serialize), but just today I was wondering if this was the right name. It's bit of an odd thing to name, since you're taking something that serializable and serializing it into a `Value`. `serde_json` exposes the functionality under a standalone function named [`to_value()`](https://docs.rs/serde_json/latest/serde_json/fn.to_value.html), circumnavigating the issue entirely.
