### ISSUE TITLE
`Object::len()` and `Object::is_empty()` conflict with inherent `len()`, `is_empty()` 

### ISSUE THREAD

**Issue by SergioBenitez** [mitsuhiko/minijinja#474]
Calling `self.len()` inside of any method implementation (in particular, `enumerate()`) calls the trait method, which is unlikely to be what's desired. The only way to prevent this is to rename `len()` and `is_empty()` to something else.

I would suggest `length()` or `enumerator_len()` instead of `len()`. For `is_empty()`, maybe `has_no_elements()` or `is_void()` or `is_vacant()`?

**Comment by mitsuhiko** [comment]
Yeah that's surprisingly annoying.  In the rest of the engine `is_empty` is just `is_false`.  I just never really liked that name because it's not literally false, but false as far as the conditionals is concerned, but we could use this here too.  Then at least it's consistent.  I think `enumerator_len` is reasonable because you're supposed to match them anyways and that way this is more explicit.

**Comment by mitsuhiko** [comment]
Maybe `Value::is_true` and `Object::is_empty` should just both become `is_truthy`.  That term is relatively popular in the JavaScript world.  Or `is_truish`.
