### ISSUE TITLE
Environment::add_and_get_template functon

### ISSUE THREAD

**Issue by Dushistov** [mitsuhiko/minijinja#58]
When "report" is not often used function there is no sense
to cache `Environment` between calls, so code to generate
reports looks like this:

```
env.add_template("report1", report1_html)?;
let html_tmpl = env.get_template("report1")?;
```

it would be nice to have function like `add_and_get_template`:
```
let html_tmpl = env.add_and_get_template("report1", report1_html)?;
```

**Comment by mitsuhiko** [comment]
I think it's better for users to build their own helpers around that if they think this is useful. Generally speaking it's not a good idea to re-create the environment due to the parsing and compilation overhead of the template. It's better to stash it into a `once_cell` or similar. So API wise I do not want to encourage not reusing the environment.

In which situation is it preferrable to re-create the environment?

**Comment by Dushistov** [comment]
> In which situation is it preferrable to re-create the environment?

Html generation takes around ~100 µs. I mean `add_template` + `get_template` + `render`.
While for my project even ~50ms is ok, because of this is GUI application with one user at time.
I don't see any reason to waste memory for `Environment` caching.
